### ISSUE TITLE
Migration is backwards-incompatible

### ISSUE THREAD

**Issue by mariusklocke** [ratepay/shopware6-module#61]
I think there is a misunterstanding about Shopware 6 Migrations in your plugin code. I am referring to `Migration1615564688AdminOrder`.

Your update-Method in that migration does backward-incompatible schema changes by changing column names. The update-Method should modify the database in backwards-compatible manner. So, if you want to change a column name or datatype, you have to:
* Create new column
* Populate new column with data from old column
* Create a trigger to populate the new column when the old column gets updated

In updateDestructive you should:
* Drop the old column
* Drop the trigger

In `Migration1615564688AdminOrder` the developer seems to have confused `updateDestructive` with a `down` or `rollback` method. A rollback-mechanism is (sadly) not specified by Shopware.

Furthermore if you change columns from `TINYINT(1) NULL` to `TINYINT(1) NOT NULL DEFAULT '0'`, you cannot assume the database will convert `NULL` values to `0` when you change the datatype. Our MariaDB 10.4.18 raised on an error on that. We had to use an UPDATE-Query before.

Please do not modify your existing migrations, but keep this in mind with future migrations.

Link to Shopware documentation: https://developer.shopware.com/docs/concepts/framework/migrations#modifying-the-database

**Comment by rommelfreddy** [comment]
Hello @mariusklocke 

Thank you for your report!

You are absolutely right. 
I confused `updateDestructive` with `rollback`.

So i removed the code from the `updateDestructive`-Method, to prevent the execution of the statements. 

We decided to make not a big migration script, cause the field `backend` has not been filled before this migration/release. 
It was only a "placeholder" for the upcoming release with the admin-orders.

But you are right, that we can not assume that the database will update the values, of the value is NULL, during an update from `NULL` to `NOT NULL`.
So I set the values to `NULL` before the update of the column definition. 

Contrary to your recommendation, I updated the migration to prevent migration-issues with installations which are lower than this migration. 
https://github.com/ratepay/shopware6-module/commit/3a033aa52952baefa5f21993c5f93690d3400832
